server:
  port: 8000

spring:
  application:
    name: gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: api-test
          uri: http://localhost:8080
          predicates:
            - Path=/api/hello/**
